spring:
  application:
    name: msclientes

#porta aleatória
server:
  port: 0

#conexão com o eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    #está referenciando o nome da aplicação